---
title: "Key messages"
sidebar: false
---

------------------------------------------------------------------------

# Overview

South Africa has exceptional biodiversity, characterised by a wide variety of ecosystem types, high species richness and high levels of endemism. South Africa's biodiversity provides an array of benefits1 to the economy, society and human wellbeing. These benefits that nature provides are dependent on intact ecosystems, healthy species populations and genetic diversity.

The NBA is the primary tool for monitoring and reporting on the state of biodiversity in South Africa and informs policies, strategic objectives and activities for managing and conserving biodiversity more effectively. The NBA is especially important for informing the National Biodiversity Strategy and Action Plan (NBSAP), the National Biodiversity Framework (NBF) and the National Protected Area Expansion Strategy (NPAES), and also informs other national strategies and frameworks across a range of sectors, such as the National Spatial Development Framework, the National Water and Sanitation Master Plan and the National Biodiversity Economy Strategy.

## South Africa's biodiversity provides benefits to people

**Biodiversity provides jobs**

South Africa's biodiversity provides substantial employment in a range of sectors (established but incomplete). Continued investment in managing and conserving biodiversity is essential so that jobs that depend on biodiversity can continue to increase. Jobs directly related to biodiversity total more than 418 000, and this is likely an underestimate. This level of employment is comparable to that of the mining sector. For every job dedicated to conserving biodiversity (e.g. in protected areas or conservation authorities), there are at least five other jobs that depend directly on biodiversity use. These jobs are in sectors such as fisheries, wildlife ranching, biodiversity-based tourism, traditional medicine and indigenous tea production.

## Healthy ecosystems are essential for water security

Rivers, wetlands and their catchment areas are crucial ecological infrastructure for water security, often complementing built infrastructure, but the benefits from some of these ecosystems are currently compromised by their poor ecological condition (well established). Water security can be improved through integrated management of natural resources in Strategic Water Source Areas as well as other key catchments, including protection and restoration in some cases.

## Water flowing into the sea provides multiple benefits to people

Freshwater flowing from rivers through estuaries into the sea is not wasted, and is essential for coastal and marine food production, livelihoods, tourism and future climate change resilience (established but incomplete). Through appropriate management, South Africa can maintain the vital freshwater flows that reach the coast.

## Small high-value ecosystem types take up just 5% of South Africa's territory, but provide disproportionate benefits to people

Certain small ecosystem types function as crucial ecological infrastructure and, despite their small footprint, provide multiple benefits to society (established but incomplete). Managing, protecting and restoring these small, high-value.

## Benefits from fishing are at risk, including food and job security

Estuarine and marine ecosystems provide South Africans with food and livelihoods by providing a basis for fishing -- whether commercial, subsistence or recreational. Yet many fish stocks are overexploited and many fish species are threatened (well established). While a range of plans are in place to ensure that fisheries are sustainable, better practices to rebuild stocks of priority species are needed, as well as reliable data and sufficient capacity for undertaking regular stock assessments.

## South Africa's biodiversity is under pressure, but solutions are at hand
