project:
  type: website

website:
  title: "NBA 2025 website structure"
  reader-mode: false
  bread-crumbs: false
  back-to-top-navigation: true

  navbar:
    left:
      - text: Home
        href: index.qmd
   
      - text: About
        menu:
          - text: "Introduction"
            href: Contents/0. About/0. Introduction.qmd        
          - text: "About the NBA"
            href: Contents/0. About/1. About the NBA.qmd
          - text: "How is NBA used"
            href: Contents/0. About/2.1 How NBA input datasets are used.qmd
          - text: "Biodiversity profile"
            href: Contents/0. About/3. Biodiversity profile.qmd
            
      - text: "Key messages"
        href: Contents/1. Key messages/Key messages.qmd

      
      - text: "Integrated findings"
        menu: 
          - text: "National Headline indicators"
            href: Contents/2. Integrated findings/Headline indicators/Headline indicators overview.qmd
          - text: "Pressures on South Africa's biodiversity"
            href: Contents/2. Integrated findings/Pressures/Pressures overview.qmd
        
      - text: "Findings by realm"
        href: RealmListing.qmd
      
      - text: Species
        href: SpeciesListing.qmd
      
      - text: "Priority actions & responses"
        menu:
          - text: "Priority actions for improving future NBAs"
            href: Contents/5. Priority actions and responses/Priority actions/Actions overview.qmd
          - text: "Responses for managing and conserving biodiversity"
            href: Contents/5. Priority actions and responses/Priority responses/Responses overview.qmd

  sidebar:
  - id: "How the NBA is used"
    style: "docked"
  - section: "**Contents**"
    contents:
      - text: "How the NBA input datasets used"
        href: Contents/0. About/2.1 How NBA input datasets are used.qmd
      - text: "Direct links between NBA and MEA indicators"
        href: Contents/0. About/2.2 Direct links between NBA and MEA indicators.qmd
        
    
  - id: "National Headline indicators"
    style: "docked"
    contents:
      - Contents/2. Integrated findings/Headline indicators/Headline indicators overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Ecosystem indicators"
            href: Contents/2. Integrated findings/Headline indicators/Ecosystems.qmd
          - text: "Species indicators"
            href: Contents/2. Integrated findings/Headline indicators/Species.qmd    
          - text: "Genetic diversity"
            href: Contents/2. Integrated findings/Headline indicators/Genetic diversity.qmd     
            
  - id: "Pressures on South Africa's biodiversity"
    style: "docked"
    contents:
      - Contents/2. Integrated findings/Pressures/Pressures overview.qmd
      - section: "**Contents**" 
        contents:
          - text: "Pressures on ecosystems"
            href: Contents/2. Integrated findings/Pressures/Pressures on ecosystems.qmd    
          - text: "Pressures on species"
            href: Contents/2. Integrated findings/Pressures/Pressures on species.qmd 
          - text: "Ecological condition"
            href: Contents/2. Integrated findings/Pressures/Ecological condition.qmd   
            
  - id: "Terrestrial realm"  
    style: "docked"
    contents:
      - Contents/3. Findings by realm/1. Terrestrial/Terrestrial overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Ecosystems"
            href: Contents/3. Findings by realm/1. Terrestrial/Terrestrial ecosystems.qmd
          - text: "Ecological condition"
            href: Contents/3. Findings by realm/1. Terrestrial/Terrestrial ecological condition.qmd    
          - text: "Red List of Ecosystems"
            href: Contents/3. Findings by realm/1. Terrestrial/Terrestrial RLE.qmd 
          - text: "Protection Level"
            href: Contents/3. Findings by realm/1. Terrestrial/Terrestrial PL.qmd 
          - text: "Species"
            href: Contents/3. Findings by realm/1. Terrestrial/Terrestrial species.qmd 
            
  - id: "Freshwater (inland aqauatic) realm"
    style: "docked"
    contents:
      - Contents/3. Findings by realm/2. Freshwater/Freshwater overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Ecosystems"
            href: Contents/3. Findings by realm/2. Freshwater/Freshwater ecosystems.qmd
          - text: "Ecological condition"
            href: Contents/3. Findings by realm/2. Freshwater/Freshwater ecological condition.qmd    
          - text: "Red List of Ecosystems"
            href: Contents/3. Findings by realm/2. Freshwater/Freshwater RLE.qmd 
          - text: "Protection Level"
            href: Contents/3. Findings by realm/2. Freshwater/Freshwater PL.qmd 
          - text: "Species"
            href: Contents/3. Findings by realm/2. Freshwater/Freshwater species.qmd   
            
  - id: "Estuarine realm"
    style: "docked"
    contents:
      - Contents/3. Findings by realm/3. Estuarine/Estuarine overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Ecosystems"
            href: Contents/3. Findings by realm/3. Estuarine/Estuarine ecosystems.qmd
          - text: "Ecological condition"
            href: Contents/3. Findings by realm/3. Estuarine/Estuarine ecological condition.qmd    
          - text: "Red List of Ecosystems"
            href: Contents/3. Findings by realm/3. Estuarine/Estuarine RLE.qmd 
          - text: "Protection Level"
            href: Contents/3. Findings by realm/3. Estuarine/Estuarine PL.qmd 
          - text: "Species"
            href: Contents/3. Findings by realm/3. Estuarine/Estuarine species.qmd             

  - id: "Marine realm"
    style: "docked"
    contents:
      - Contents/3. Findings by realm/4. Marine/Marine overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Ecosystems"
            href: Contents/3. Findings by realm/4. Marine/Marine ecosystems.qmd
          - text: "Ecological condition"
            href: Contents/3. Findings by realm/4. Marine/Marine ecological condition.qmd    
          - text: "Red List of Ecosystems"
            href: Contents/3. Findings by realm/4. Marine/Marine RLE.qmd 
          - text: "Protection Level"
            href: Contents/3. Findings by realm/4. Marine/Marine PL.qmd 
          - text: "Species"
            href: Contents/3. Findings by realm/4. Marine/Marine species.qmd 

  - id: "Coast cross-cutting realm"  
    style: "docked"
    contents:
      - Contents/3. Findings by realm/5. Coast/Coast overview.qmd
      - section: "**Contents**" 
        contents:
          - text: "Ecosystems"
            href: Contents/3. Findings by realm/5. Coast/Coast ecosystems.qmd
          - text: "Ecological condition"
            href: Contents/3. Findings by realm/5. Coast/Coast ecological condition.qmd    
          - text: "Red List of Ecosystems"
            href: Contents/3. Findings by realm/5. Coast/Coast RLE.qmd 
          - text: "Effectiveness and impact responses"
            href: Contents/3. Findings by realm/5. Coast/Effectiveness and impact responses.qmd 
          - text: "Species"
            href: Contents/3. Findings by realm/5. Coast/Coast species.qmd 
      
  
  - id: "Invertebrates"
    style: "docked"
    contents: 
      - Contents/4. Species/4. Invertebrates/Invertebrates.qmd
      - section: "**Contents**"
        contents: 
          - text: "Bees"
            href: Contents/4. Species/4. Invertebrates/Bees.qmd
          - text: "Branchiopoda"
            href: Contents/4. Species/4. Invertebrates/Branchiopoda.qmd
          - text: "Butterflies"
            href: Contents/4. Species/4. Invertebrates/Butterflies.qmd            
          - text: "Crabs"
            href: Contents/4. Species/4. Invertebrates/Crabs.qmd
          - text: "Dragonflies"
            href: Contents/4. Species/4. Invertebrates/Dragonflies.qmd            
          - text: "Estuary invertebrates"
            href: Contents/4. Species/4. Invertebrates/Estuary invertebrates.qmd            
          - text: "Mammals"
            href: Contents/4. Species/4. Invertebrates/Mammals.qmd            
          - text: "Mollusca"
            href: Contents/4. Species/4. Invertebrates/Mollusca.qmd            
          - text: "Plants"
            href: Contents/4. Species/4. Invertebrates/Plants.qmd
          - text: "Reptiles"
            href: Contents/4. Species/4. Invertebrates/Reptiles.qmd            
          - text: "Spiders"
            href: Contents/4. Species/4. Invertebrates/Spiders.qmd
            
  
  - id: "Priority actions for improving future NBAs"
    style: "docked"
    contents: 
      - Contents/5. Priority actions and responses/Priority actions/Actions overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Knowledge Gaps and Research Priorities for Strengthening the NBA"
            href: Contents/5. Priority actions and responses/Priority actions/Knowledge gaps.qmd
          - text: "Review of tools used to measure genetic diversity"
            href: Contents/5. Priority actions and responses/Priority actions/Review of genetic diver.qmd
            
  - id: "Priority responses overview"
    style: docked
    contents:
      - Contents/5. Priority actions and responses/Priority responses/Responses overview.qmd
      - section: "**Contents**"
        contents:
          - text: "Avoid biodiversity loss"
            href: Contents/5. Priority actions and responses/Priority responses/Avoid loss.qmd 
          - text: "Biodiversity protection"
            href: Contents/5. Priority actions and responses/Priority responses/Protect.qmd
          - text: "Biodiversity restoration"
            href: Contents/5. Priority actions and responses/Priority responses/Restore.qmd        
          - text: "Biodiversity conservation"
            href: Contents/5. Priority actions and responses/Priority responses/Bio conservation.qmd
          - text: "Effectiveness and impact of responses"
            href: Contents/5. Priority actions and responses/Priority responses/Effectiveness impact.qmd   
           
  page-footer:
      left: |
       [![](/images/SANBI_logo.png){width=200px}](https://www.sanbi.org/)

      center: |
        Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=80px}]

      right: |
        [![](/images/logo-environmental-affairs.jpg){width=200px}](https://www.dffe.gov.za/reports)   


format:
  html:
    number-sections: true
    #number-depth: 6
    linestretch: 1.9
    toc-title: "On this page"
    toc: true
    anchor-sections: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    embed-resources: true # ensure that all resources (like images, CSS, and other assets) are embedded directly into the HTML files useful for offline access or distributing the site without needing external links to resources.
    
    theme:
      light: cosmo
      dark: darkly 
      
    grid:
      sidebar-width: 350px
      body-width: 1200px
      margin-width: 400px
      
execute: 
  warning: false
  message: false
  
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  title-delim: "**:**"
      


freeze: true

editor: visual


